---
- name: Check services
  hosts: staging
  # need to use become since I'm connecting using personal private key
  become: true
  # switch user as dev
  become_user: dev
  vars:
    project_dir: /home/dev/web-projects/pycontw-2023-ansible

  tasks:
    - name: Ensure that Docker for python is present (docker in pip)
      community.general.python_requirements_info:
        dependencies:
          - docker

    - name: Create a directory if it does not exist
      ansible.builtin.file:
        path: "{{ project_dir }}"
        state: directory

    - name: Copy entire project files to remote server
      ansible.posix.synchronize:
        src: ./
        dest: "{{ project_dir }}"
        delete: true

    - name: Ensure docker network network-2023 exists
      community.docker.docker_network:
        name: network-2023

    - name: Build and start service
      community.docker.docker_compose:
        project_src: "{{ project_dir }}"
        build: true
        # try to build first, without up the service
        state: absent
